services:
  # Nossa aplicação Go (Máquina de Estado e Regras de Negócio)
  ledger-app-1:
    build:
      context: .
      dockerfile: ./ledger/Dockerfile
    ports:
      - "26658:26658" # Porta ABCI
    networks:
      - consorcio-net

  # O Motor de Consenso P2P (CometBFT)
  cometbft-node-1:
    image: cometbft/cometbft:v0.38.0
    command: node --proxy_app=tcp://ledger-app-1:26658 --rpc.laddr=tcp://0.0.0.0:26657
    ports:
      - "26657:26657" # Porta RPC 
      - "26656:26656" # Porta P2P 
    networks:
      - consorcio-net
    depends_on:
      - ledger-app-1

  # O Módulo Cliente (CLI)
  cliente-cli:
    build:
      context: .
      dockerfile: ./cliente/Dockerfile # Certifique-se de que o caminho bate com a sua pasta
    networks:
      - consorcio-net
    # Mantém o contêiner vivo infinitamente no background para podermos enviar comandos
    command: tail -f /dev/null
    depends_on:
      - cometbft-node-1

networks:
  consorcio-net:
    driver: bridge